version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: yahoo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: yahoo
      DB_USER: postgres
      DB_PASS: secret
    depends_on:
      - db

volumes:
  dbdata:
