services:
  web:
    build: .
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  notifier:
    build: ./notifier
    depends_on:
      - rabbitmq
    restart: unless-stopped

  logs:
    image: busybox:latest
    command: "sh -c \"while true; do echo '$(date): Dashboard is running' >> /logs/app.log; sleep 30; done\""
    volumes:
      - ./logs:/logs
    restart: unless-stopped

