services:
  web:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: unless-stopped

  logs:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./logs/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    depends_on:
      - web
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:

